// Generated by sdkgen go-mcp target.
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/modelcontextprotocol/go-sdk/mcp"
	sdk "github.com/voxgig-sdk/financial-data-sdk/go"
)

// Args is the common argument shape for both tools. `entity` selects
// the SDK entity to operate on; `query` is the optional reqmatch /
// reqdata map passed through to the SDK. For load, `query` should be
// `{"id": <value>}`. For list, omit `query` or pass an empty map.
type Args struct {
	Entity string         `json:"entity" jsonschema:"basic_information | crypto_currency | derivatives_data | esg_data | etf_data | event_calendar | financial_ratio | financial_statement | forex_data | insider_trading | institutional_trading | investment_adviser | market_data | market_index | market_new | miscellaneous_data | mutual_fund | symbol_list"`
	Query  map[string]any `json:"query,omitempty" jsonschema:"optional match map e.g. {\"id\":1} for load, omit for list"`
}

func registerTools(server *mcp.Server, client *sdk.FinancialDataSDK) {
	mcp.AddTool(server, &mcp.Tool{
		Name: "financial-data_list",
		Description: "List records from FinancialData. " +
			"Args: entity (one of the supported SDK entities), query (optional filter map). " +
			"Returns the first page of records as JSON.",
	}, func(ctx context.Context, req *mcp.CallToolRequest, args Args) (*mcp.CallToolResult, any, error) {
		return runOp(client, "list", args)
	})

	mcp.AddTool(server, &mcp.Tool{
		Name: "financial-data_load",
		Description: "Load a single record from FinancialData. " +
			"Args: entity, query ({\"id\":N} required). Returns the record as JSON.",
	}, func(ctx context.Context, req *mcp.CallToolRequest, args Args) (*mcp.CallToolResult, any, error) {
		return runOp(client, "load", args)
	})
}

func runOp(client *sdk.FinancialDataSDK, op string, args Args) (*mcp.CallToolResult, any, error) {
	ent, err := entityFor(client, args.Entity)
	if err != nil {
		return toolError(err.Error())
	}

	var result any
	switch op {
	case "list":
		result, err = ent.List(args.Query, nil)
	case "load":
		result, err = ent.Load(args.Query, nil)
	default:
		return toolError(fmt.Sprintf("unknown op %q", op))
	}
	if err != nil {
		return toolError(err.Error())
	}

	// SDK returns *Entity wrappers; unwrap each via .Data() to get a
	// plain map[string]any (or []any of maps for list) suitable for
	// JSON marshalling.
	data := extractData(result)
	body, err := json.MarshalIndent(data, "", "  ")
	if err != nil {
		return toolError(fmt.Sprintf("marshal: %v", err))
	}
	return &mcp.CallToolResult{
		Content: []mcp.Content{
			&mcp.TextContent{Text: string(body)},
		},
	}, data, nil
}

// entityFor dispatches on the lowercase entity name. The generator
// emits one `case "<name>":` per entity defined in the SDK model.
func entityFor(client *sdk.FinancialDataSDK, name string) (sdk.FinancialDataEntity, error) {
	switch strings.ToLower(name) {
	case "basic_information":
		return client.BasicInformation(nil), nil
	case "crypto_currency":
		return client.CryptoCurrency(nil), nil
	case "derivatives_data":
		return client.DerivativesData(nil), nil
	case "esg_data":
		return client.EsgData(nil), nil
	case "etf_data":
		return client.EtfData(nil), nil
	case "event_calendar":
		return client.EventCalendar(nil), nil
	case "financial_ratio":
		return client.FinancialRatio(nil), nil
	case "financial_statement":
		return client.FinancialStatement(nil), nil
	case "forex_data":
		return client.ForexData(nil), nil
	case "insider_trading":
		return client.InsiderTrading(nil), nil
	case "institutional_trading":
		return client.InstitutionalTrading(nil), nil
	case "investment_adviser":
		return client.InvestmentAdviser(nil), nil
	case "market_data":
		return client.MarketData(nil), nil
	case "market_index":
		return client.MarketIndex(nil), nil
	case "market_new":
		return client.MarketNew(nil), nil
	case "miscellaneous_data":
		return client.MiscellaneousData(nil), nil
	case "mutual_fund":
		return client.MutualFund(nil), nil
	case "symbol_list":
		return client.SymbolList(nil), nil

	}
	return nil, fmt.Errorf("unknown entity %q", name)
}

// extractData walks an SDK result and replaces any sdk.Entity wrapper
// with its underlying record (via .Data()).
func extractData(x any) any {
	switch v := x.(type) {
	case sdk.Entity:
		return extractData(v.Data())
	case []any:
		out := make([]any, len(v))
		for i, e := range v {
			out[i] = extractData(e)
		}
		return out
	case map[string]any:
		out := make(map[string]any, len(v))
		for k, vv := range v {
			out[k] = extractData(vv)
		}
		return out
	}
	return x
}

func toolError(msg string) (*mcp.CallToolResult, any, error) {
	return &mcp.CallToolResult{
		IsError: true,
		Content: []mcp.Content{
			&mcp.TextContent{Text: msg},
		},
	}, nil, nil
}
